apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonAnnotations:
  cosi.storage.k8s.io/authors: "Kubernetes Authors"
  cosi.storage.k8s.io/license: "Apache V2"
  cosi.storage.k8s.io/support: "https://github.com/kubernetes-sigs/container-object-storage-api"
commonLabels:
  cosi.storage.k8s.io/version: "dev"

resources:
  - resources/daemonset.yaml
  - resources/sa.yaml
  - resources/rbac.yaml
