---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-csi-adapter-role
  namespace: default
  labels:
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
rules:
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["bucketrequests", "bucketaccessrequests"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["buckets", "bucketaccesses"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["bucketclass","bucketaccessclass"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-csi-adapter
  namespace: default
  labels:
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
subjects:
  - kind: ServiceAccount
    name: objectstorage-csi-adapter-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: objectstorage-csi-adapter-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-csi-adapter
  namespace: default
  labels:
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-csi-adapter
  namespace: default
  labels:
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
subjects:
  - kind: ServiceAccount
    name: objectstorage-csi-adapter-sa
    namespace: default
roleRef:
  kind: Role
  name: objectstorage-csi-adapter
  apiGroup: rbac.authorization.k8s.io
