---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: objectstorage-csi-adapter-sa
  labels:
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
