#
# Note, this resource would typically be created by COSI and not the user or kubeadmin
# with an exception for brownfield use cases, in which case the kubeadmin should create
# the bucket.
#
kind: BucketAccess
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: sample-ba
spec:
  bucketAccessRequest:
    apiVersion: objectstorage.k8s.io/v1alpha1
    kind: BucketAccessRequest
    name: sample-bar
  bucketInstanceName: sample-b
  mintedSecretName: sample-secret
  provisioner: sample
status:
  accessGranted: true
