#
# Note, this resource would typically be created by COSI and not the user or kubeadmin
# with an exception for brownfield use cases, in which case the kubeadmin should create
# the bucket.
#
kind: Bucket
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: sample-b
spec:
  bucketClassName: sample-bc
  bucketRequest:
    apiVersion: objectstorage.k8s.io/v1alpha1
    kind: BucketRequest
    name: sample-br
  protocol:
    name: s3
    s3:
      bucketName: sampleBucket
      endpoint: sampleBucket.com
      region: us-east-1
      signatureVersion: s3v4
  provisioner: sample 
  retentionPolicy: retain
status:
  bucketAvailable: true
