apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: web
    image: quay.io/krishchow/cosi-app
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: cosi-secrets
      mountPath: /data/cosi
    env:
      - name: PORT
        value: "3000"
      - name: MOUNT_PATH
        value: "/data/cosi"
  volumes:
  - name: cosi-secrets
    csi:
      driver: objectstorage.k8s.io
      volumeAttributes:
        bar-name: sample-bar
        bar-namespace: default
